//! # nexrad-level3
//!
//! A decoder for NEXRAD Weather Radar Level III products. Level III products are
//! derived/processed radar outputs generated by the Radar Product Generator (RPG),
//! as opposed to the raw base moments found in Level II Archive II data.
//!
//! ## Crate Boundaries
//!
//! ### Responsibilities ✓
//! - Defining data model types for Level III products (headers, symbology, radial/raster packets)
//! - Decoding Level III binary product messages (ICD 2620001) from byte slices
//! - Stripping optional WMO/AWIPS headers and decompressing zlib payloads
//!
//! ### Constraints ✗
//! - No network I/O or file system access
//! - No rendering or visualization

#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![warn(clippy::correctness)]
#![allow(clippy::too_many_arguments)]
#![deny(missing_docs)]

pub mod decode;
pub mod model;
pub mod result;
