[workspace]
resolver = "2"
members = [
    "rustdar-platform",
    "rustdar-android",
    "rustdar-android-theme",
    "rustdar-egui",
    "rustdar-radar",
    "rustdar-overlays",
    "nexrad-level3",
]

[profile.dev]
# Only optimize dependencies (not workspace code) to preserve debuggability
strip = true

[profile.dev.package."*"]
opt-level = "s"

[profile.release]
strip = true
opt-level = "s"
lto = true
