[package]
name = "rustdar-egui"
version.workspace = true
edition.workspace = true

[dependencies]
rustdar-radar = { workspace = true }
rustdar-overlays = { workspace = true }
rustdar-units = { workspace = true }
rustdar-gps = { workspace = true }
chrono = { workspace = true }
egui = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkers = { workspace = true }
