//! Hybrid Hydrometeor Classification (the RPG's product 177, AWIPS `HHC`)
//! computed locally by compositing the per-tilt classification of
//! [`crate::hca`] down the hybrid scan.
//!
//! Product 177 is generated by the **dual-pol QPE rate task**
//! `cpc013/tsk009` (`qperate`), whose `HHC_Buf_t` intermediate
//! (`QPEHHC`, 360° × 920 × 0.25 km of internal class numbers) is formatted
//! by `cpc024/tsk004` (`hhc8bit`). Everything below is transcribed from the
//! CODE Build 21.0r1.7 public source, with the fleet defaults from
//! `cpc104/lib006/dp_precip.alg`; the hybrid-scan concept is Fulton,
//! Breidenbach, Seo, Miller, O'Bannon 1998, "The WSR-88D Rainfall
//! Algorithm" (Weather and Forecasting 13, 377–395), reworked for dual-pol
//! per the QPE AEL.
//!
//! **The compositing rule** (`qperate_build_RainfallRate.c`'s
//! `build_RR_Polar_Grid` / `Add_bin_to_RR_Polar_Grid`): on the lowest
//! elevation every (azimuth, bin) is tried; a bin is **used** — its
//! internal hydro class stored into `HybridHCA` — when a precipitation
//! rate can be computed there, and otherwise goes onto a *hybrid list*
//! retried at each higher elevation until it fills or the volume ends.
//! Per `Add_bin` + `qperate_comp_IRRate.c`, a bin at one elevation:
//!
//! * is **skipped upward** when its class is GC or UK (or the gate is
//!   beyond the moment), when the radial is bad, when blockage exceeds
//!   95%, or when it sits in an exclusion zone (`Num_zones = 0` in the
//!   fleet default — none);
//! * **fills with rate 0** when the class is BI or NE — biology and
//!   no-echo are answers, not gaps, so a low-tilt clear bin never shows a
//!   higher tilt's echo;
//! * otherwise needs the gate's **met signal ≥ 80** (the radial's `DMET`;
//!   with `metsignal_processing = OFF` the check is ρ ≥ `art_corr` on
//!   non-attenuated radials instead), and then a valid rate by class:
//!   R(Z, ZDR) for RA/BD (needs Z and ZDR), R(Z)-multiples for GR/IC/WS/DS
//!   (needs Z), R(KDP)-with-R(Z)-fallback for HR above 45 dBZ and for RH
//!   at or below the melting-layer `bin_tt` (needs Z, or a non-negative
//!   KDP), R(Z, ZDR) for HR at ≤ 45 dBZ, R(Z)·0.8 for RH above `bin_tt`;
//!   on a high-attenuation radial a failed rate re-tries R(Z, ZDR), R(Z),
//!   R(KDP) in order (`AEL 3.1.2.4`). Only **validity** decides the HHC —
//!   the rate magnitudes feed the rate products, not this one.
//!
//!
//!
//! **SAILS/MRLE** (`Sails_opt = YES`, CCR NA17-00126): bins that computed
//! a good rate on base cut *k* (k ≤ 4) are recorded, and each supplemental
//! low cut re-computes exactly those bins — a failure keeps the original
//! value. Supplemental cuts are recognized here as dual-pol tilts whose
//! target angle repeats an earlier tilt's (within 0.3°), the archive's
//! visible form of the VCP's supplemental flags.
//!
//! **Termination** (`Grid_is_full = 99.9`): without supplemental cuts the
//! ladder stops once ≥ 99.9% of the 360 × 920 grid is filled (or tilts run
//! out); with SAILS/MRLE in the VCP the whole volume is processed.
//!
//! **Encoding** (`hhc8bit.c`): the product's data levels are
//! `Class_external` of the stored internal class — the same 10…140 codes
//! as product 165 except that the **hail subclasses do not exist here**
//! (`HybridHCA` stores the internal class, so RH cores read 100, never
//! 110/120), and unfilled/NE/U0 bins read level 0 (`MISSING_DATA`, CCR
//! NA16-00223). PDB scale 1 / offset 0, elevation number 0 (a volume
//! product), 920 bins × 0.25 km = the 230 km domain, one product per
//! volume plus one intermediate per SAILS scan (the end-of-volume object
//! is the full composite this module reproduces — the twin harness pairs
//! the volume's **latest** HHC object for that reason).

use crate::dpprep::{DpInput, ReflCappi, combine_sweep_dp, resample_to_polar_grid};
use crate::hca::{
    BD, BI, CLASS_EXTERNAL, DS, GC, GR, HR, HcaOptions, HsdaHeights, IC, MeltingLayer, NE, NO_DATA,
    RA, RH, UK, WS, beam_ml_intersection, classify_radial, merge_split_cut_doppler, radial_fields,
    resolve_init_fdp,
};
use crate::kdp::KdpParams;
use crate::par::*;
use nexrad_model::data::Radial;

/// The QPEHHC grid: 360 × 920 gates of 0.25 km (`dp_Consts.h`).
pub const HHC_BINS: usize = 920;
pub(crate) const HHC_AZ: usize = 360;

/// `Grid_is_full`, percent.
const GRID_IS_FULL_PCT: f64 = 99.9;
/// `Hr_HighZThresh`: above this, HR rates by R(KDP) instead of R(Z, ZDR).
const HR_HIGH_Z_THRESH: f64 = 45.0;
/// How many base cuts keep SAILS/MRLE replacement lists (list1–list4).
const MAX_SUPP_LISTS: usize = 4;
/// Supplemental cuts repeat an earlier target angle within this.
const SUPP_ANGLE_TOL: f32 = 0.3;

/// One prepared tilt's per-azimuth rows: the classification and the fields
/// the usability check reads, plus the melting-layer bins per azimuth.
/// `None` where the tilt carried no radial for that whole degree.
pub(crate) type Tilt = Vec<Option<TiltRow>>;

pub(crate) struct TiltRow {
    pub(crate) class: Vec<usize>,
    pub(crate) smz: Vec<f64>,
    pub(crate) zdr: Vec<f64>,
    pub(crate) kdp: Vec<f64>,
    pub(crate) met: Vec<f64>,
    pub(crate) hatt: bool,
    /// `beam_edge_top`: where the beam's lower edge crosses the melting
    /// layer's top, in DP bins.
    pub(crate) bin_tt: i64,
}

/// The derived hybrid classification, at the product's own geometry.
pub struct DerivedHhc {
    /// `[azimuth 0..360][bin 0..920]`, the product's external class codes;
    /// `NaN` where unfilled or the stored class encodes level 0 (NE/U0).
    pub values: Vec<Vec<f32>>,
    /// Range to the centre of bin 0, km, and the bin size.
    pub first_gate_km: f64,
    pub gate_interval_km: f64,
    /// `pct_hybrate_filled`: percent of the grid that computed a rate.
    pub pct_filled: f64,
    /// `highest_elang`: the highest base elevation processed, degrees.
    pub highest_elev_deg: f64,
}

impl DerivedHhc {
    pub fn to_polar_grid(&self) -> Vec<Vec<f32>> {
        let azimuths: Vec<f64> = (0..HHC_AZ).map(|az| az as f64 + 0.5).collect();
        resample_to_polar_grid(
            &self.values,
            &azimuths,
            self.first_gate_km,
            self.gate_interval_km,
            1.0,
        )
    }
}

/// Group a volume's sweeps into the elevations the QPE chain consumes:
/// each dual-pol sweep with the split-cut Doppler partner's velocity
/// grafted in (the RPG's combined base data), in scan order. Sweeps
pub fn volume_tilts(sweeps: &[&[Radial]]) -> Vec<(f32, Vec<Radial>)> {
    let mut tilts: Vec<(f32, Vec<Radial>)> = Vec::new();
    for (i, &radials) in sweeps.iter().enumerate() {
        let Some(first) = radials
            .iter()
            .take(5)
            .find(|r| r.differential_phase().is_some())
        else {
            continue;
        };
        let eln = first.elevation_number();
        let angle = first.elevation_angle_degrees();
        let merged = if radials.iter().take(5).any(|r| r.velocity().is_some()) {
            radials.to_vec()
        } else {
            let partner = sweeps[i + 1..].iter().find_map(|s| {
                let f = s.first()?;
                (f.elevation_number() == eln + 1
                    && (f.elevation_angle_degrees() - angle).abs() < SUPP_ANGLE_TOL
                    && s.iter().take(5).any(|x| x.velocity().is_some()))
                .then_some(*s)
            });
            match partner {
                Some(cd) => merge_split_cut_doppler(radials, cd),
                None => radials.to_vec(),
            }
        };
        tilts.push((angle, merged));
    }
    tilts
}

/// Prepare one tilt: recombine, run the dpprep/QIA chain and the per-tilt
/// classification, and index the radials by whole degree.
pub(crate) fn prepare_tilt(
    radials: &[Radial],
    params: &KdpParams,
    ml: &MeltingLayer,
    hsda: &HsdaHeights,
    cappi: Option<&ReflCappi>,
    opts: HcaOptions,
) -> Option<Tilt> {
    let inputs: Vec<DpInput> = radials.iter().filter_map(DpInput::from_radial).collect();
    if inputs.is_empty() {
        return None;
    }
    let combined = combine_sweep_dp(&inputs, true);
    let init_fdp = resolve_init_fdp(params, &combined, opts.isdp_estimated);
    let dbz0 = params.dbz0.map(f64::from);
    let atmos = params.atmos_db_per_km.map(f64::from);

    let placed: Vec<(usize, TiltRow)> = combined
        .par_iter()
        .map(|c| {
            let f = radial_fields(
                c,
                init_fdp,
                dbz0,
                atmos,
                opts.quantize_transport,
                opts.metsignal,
                cappi,
            );
            let class = classify_radial(&f, ml, hsda.tw0_km_arl);
            let az = (f.az.rem_euclid(360.0)) as usize % HHC_AZ;
            let ml_bins = beam_ml_intersection(f.elev, az, f.dg, ml);
            (
                az,
                TiltRow {
                    class,
                    smz: f.smz,
                    zdr: f.zdr,
                    kdp: f.kdp,
                    met: f.met,
                    hatt: f.hatt,
                    bin_tt: ml_bins.tt,
                },
            )
        })
        .collect();

    let mut rows: Tilt = (0..HHC_AZ).map(|_| None).collect();
    for (az, row) in placed {
        rows[az] = Some(row);
    }
    Some(rows)
}

/// One volume's hybrid-scan composite, whatever the per-bin answer is.
pub(crate) struct Composite<T> {
    /// `[azimuth 0..360][bin 0..920]`, `None` where the ladder never filled.
    pub(crate) cells: Vec<Vec<Option<T>>>,
    /// Range to the centre of bin 0, km, and the bin size.
    pub(crate) first_gate_km: f64,
    pub(crate) gate_interval_km: f64,
    /// `pct_hybrate_filled`: percent of the grid that concluded an answer.
    pub(crate) pct_filled: f64,
    /// `highest_elang`: the highest base elevation processed, degrees.
    pub(crate) highest_elev_deg: f64,
}

/// **The hybrid-scan ladder** of `qperate_build_RainfallRate.c`
/// (`build_RR_Polar_Grid` / `Add_bin_to_RR_Polar_Grid`), generic over the
pub(crate) fn composite_hybrid_scan<S, T, P, A>(
    tilts: &[(f32, Vec<Radial>)],
    mut prepare: P,
    mut answer: A,
) -> Option<Composite<T>>
where
    T: Clone,
    P: FnMut(&[Radial]) -> Option<S>,
    A: FnMut(&S, usize, usize) -> Option<T>,
{
    // Mark supplemental cuts: a repeat of an earlier tilt's target angle.
    let mut base_angles: Vec<f32> = Vec::new();
    let mut marked: Vec<(f32, &Vec<Radial>, Option<usize>)> = Vec::new();
    for (angle, radials) in tilts {
        let supplements = base_angles
            .iter()
            .position(|a| (a - angle).abs() < SUPP_ANGLE_TOL)
            .map(|k| k + 1);
        if supplements.is_none() {
            base_angles.push(*angle);
        }
        marked.push((*angle, radials, supplements));
    }
    let has_supp = marked.iter().any(|(_, _, s)| s.is_some());

    let mut geometry: Option<(f64, f64)> = None;
    let mut cells: Vec<Vec<Option<T>>> = vec![vec![None; HHC_BINS]; HHC_AZ];
    let mut pending: Vec<(u16, u16)> = Vec::new();
    let mut lists: [Vec<(u16, u16)>; MAX_SUPP_LISTS] = Default::default();
    let mut filled: usize = 0;
    let min_bins = ((HHC_AZ * HHC_BINS) as f64 * GRID_IS_FULL_PCT * 0.01).ceil() as usize;

    let mut base_ind = 0usize;
    let mut highest_elev = 0.0f64;
    let mut done = false;
    for (angle, radials, supplements) in marked {
        if done {
            break;
        }
        let Some(tilt) = prepare(radials) else {
            continue;
        };
        if geometry.is_none()
            && let Some(input) = radials.iter().filter_map(DpInput::from_radial).next()
        {
            geometry = Some((input.dr0, input.dg));
        }

        if let Some(k) = supplements {
            if k <= MAX_SUPP_LISTS {
                for &(az, rng) in &lists[k - 1] {
                    if let Some(v) = answer(&tilt, az as usize, rng as usize) {
                        cells[az as usize][rng as usize] = Some(v);
                    }
                }
            }
            continue;
        }

        base_ind += 1;
        highest_elev = f64::from(angle);
        if base_ind == 1 {
            for (az, row) in cells.iter_mut().enumerate() {
                for (rng, cell) in row.iter_mut().enumerate() {
                    match answer(&tilt, az, rng) {
                        Some(v) => {
                            *cell = Some(v);
                            filled += 1;
                            if has_supp {
                                lists[0].push((az as u16, rng as u16));
                            }
                        }
                        None => pending.push((az as u16, rng as u16)),
                    }
                }
            }
        } else {
            let mut next_pending = Vec::with_capacity(pending.len());
            for &(az, rng) in &pending {
                match answer(&tilt, az as usize, rng as usize) {
                    Some(v) => {
                        cells[az as usize][rng as usize] = Some(v);
                        filled += 1;
                        if has_supp && base_ind <= MAX_SUPP_LISTS {
                            lists[base_ind - 1].push((az, rng));
                        }
                    }
                    None => next_pending.push((az, rng)),
                }
            }
            pending = next_pending;
        }

        if !has_supp && filled >= min_bins {
            done = true;
        }
    }
    let (first_gate_km, gate_interval_km) = geometry?;
    Some(Composite {
        cells,
        first_gate_km,
        gate_interval_km,
        pct_filled: 100.0 * filled as f64 / (HHC_AZ * HHC_BINS) as f64,
        highest_elev_deg: highest_elev,
    })
}

/// `compute_IRRate` reduced to what the HHC needs: whether this gate
/// computes a rate at this tilt. `None` means "try a higher elevation";
/// `Some(class)` fills the bin.
fn bin_outcome(row: &TiltRow, rng: usize, met_on: bool) -> Option<usize> {
    let class = *row.class.get(rng)?;
    if class == GC || class == UK {
        return None;
    }
    if class == BI || class == NE {
        return Some(class);
    }
    let z = row.smz.get(rng).copied().unwrap_or(NO_DATA);
    let zdr = row.zdr.get(rng).copied().unwrap_or(NO_DATA);
    let kdp = row.kdp.get(rng).copied().unwrap_or(NO_DATA);
    let met = row.met.get(rng).copied().unwrap_or(f64::NAN);
    let z_def = z != NO_DATA;
    let zdr_def = zdr != NO_DATA;
    let kdp_ok = kdp != NO_DATA && kdp >= 0.0;

    if met_on && (met.is_nan() || met < crate::dpprep::MET_SIG_THRESHOLD) {
        return None;
    }

    let by_class = match class {
        BD | RA => z_def && zdr_def,
        GR | IC | WS | DS => z_def,
        HR => z_def && (z > HR_HIGH_Z_THRESH || zdr_def),
        RH => {
            if (rng as i64) <= row.bin_tt {
                z_def || kdp_ok
            } else {
                z_def
            }
        }
        _ => false,
    };
    if by_class || (row.hatt && (z_def || kdp_ok)) {
        Some(class)
    } else {
        None
    }
}

/// Composite one volume's tilts into the hybrid classification.
pub fn compute_hhc(
    tilts: &[(f32, Vec<Radial>)],
    params: &KdpParams,
    ml: &MeltingLayer,
    hsda: &HsdaHeights,
    cappi: Option<&ReflCappi>,
) -> Option<DerivedHhc> {
    compute_hhc_impl(tilts, params, ml, hsda, cappi, HcaOptions::primary())
}

pub(crate) fn compute_hhc_impl(
    tilts: &[(f32, Vec<Radial>)],
    params: &KdpParams,
    ml: &MeltingLayer,
    hsda: &HsdaHeights,
    cappi: Option<&ReflCappi>,
    opts: HcaOptions,
) -> Option<DerivedHhc> {
    let composite = composite_hybrid_scan(
        tilts,
        |radials| prepare_tilt(radials, params, ml, hsda, cappi, opts),
        |tilt: &Tilt, az, rng| {
            tilt[az]
                .as_ref()
                .and_then(|row| bin_outcome(row, rng, opts.metsignal))
        },
    )?;

    let values: Vec<Vec<f32>> = composite
        .cells
        .iter()
        .map(|row| {
            row.iter()
                .map(|c| match c {
                    None => f32::NAN,
                    Some(class) => {
                        let code = CLASS_EXTERNAL[*class];
                        if code == 0.0 { f32::NAN } else { code }
                    }
                })
                .collect()
        })
        .collect();

    Some(DerivedHhc {
        values,
        first_gate_km: composite.first_gate_km,
        gate_interval_km: composite.gate_interval_km,
        pct_filled: composite.pct_filled,
        highest_elev_deg: composite.highest_elev_deg,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hca::HsdaHeights;
    use nexrad_model::data::{MomentData, Radial, RadialStatus};

    const D_GATES: usize = 400;
    const FIRST_M: u16 = 125;
    const GATE_M: u16 = 250;

    #[derive(Clone, Copy)]
    enum G {
        V(f64),
        Nd,
    }

    fn raw_of(scale: f32, offset: f32, g: G) -> u16 {
        match g {
            G::Nd => 0,
            G::V(v) => (v * f64::from(scale) + f64::from(offset)).round() as u16,
        }
    }

    fn m16(scale: f32, offset: f32, vals: &[G]) -> MomentData {
        let mut bytes = Vec::with_capacity(vals.len() * 2);
        for &g in vals {
            bytes.extend_from_slice(&raw_of(scale, offset, g).to_be_bytes());
        }
        MomentData::from_fixed_point(vals.len() as u16, FIRST_M, GATE_M, 16, scale, offset, bytes)
    }

    fn m8(scale: f32, offset: f32, vals: &[G]) -> MomentData {
        let bytes: Vec<u8> = vals
            .iter()
            .map(|&g| raw_of(scale, offset, g) as u8)
            .collect();
        MomentData::from_fixed_point(vals.len() as u16, FIRST_M, GATE_M, 8, scale, offset, bytes)
    }

    /// One tilt of 360 one-degree radials whose fields come from per-gate
    /// closures.
    fn tilt(
        elev: f32,
        z_at: &dyn Fn(usize) -> G,
        zdr_at: &dyn Fn(usize) -> G,
        rho_at: &dyn Fn(usize) -> G,
        phi_at: &dyn Fn(usize) -> G,
    ) -> Vec<Radial> {
        (0..360)
            .map(|k| {
                let z: Vec<G> = (0..D_GATES).map(z_at).collect();
                let zdr: Vec<G> = (0..D_GATES).map(zdr_at).collect();
                let rho: Vec<G> = (0..D_GATES).map(rho_at).collect();
                let phi: Vec<G> = (0..D_GATES).map(phi_at).collect();
                Radial::new(
                    0,
                    0,
                    0.5 + k as f32,
                    1.0,
                    RadialStatus::IntermediateRadialData,
                    1,
                    elev,
                    Some(m8(2.0, 66.0, &z)),
                    None,
                    None,
                    Some(m8(16.0, 128.0, &zdr)),
                    Some(m16(10.0, 2.0, &phi)),
                    Some(m16(500.0, 2.0, &rho)),
                    None,
                )
            })
            .collect()
    }

    fn params() -> KdpParams {
        KdpParams {
            init_fdp_deg: Some(60.0),
            dbz0: Some(-40.0),
            atmos_db_per_km: Some(-0.012),
            isdp_est_deg: None,
        }
    }

    fn hsda_far() -> HsdaHeights {
        HsdaHeights {
            tw0_km_arl: 100.0,
            twm25_km_arl: 105.0,
        }
    }

    fn rain_tilt(elev: f32, z_span: std::ops::Range<usize>) -> Vec<Radial> {
        let zr = z_span.clone();
        tilt(
            elev,
            &move |i| if zr.contains(&i) { G::V(30.0) } else { G::Nd },
            &|_| G::V(1.0),
            &|_| G::V(0.99),
            &|_| G::V(60.0),
        )
    }

    #[test]
    fn rain_fills_at_the_lowest_cut() {
        let tilts = vec![(0.5f32, rain_tilt(0.5, 0..D_GATES))];
        let ml = MeltingLayer::flat(4.0);
        let d = compute_hhc(&tilts, &params(), &ml, &hsda_far(), None).expect("computes");
        assert_eq!(d.values.len(), 360);
        assert_eq!(d.values[0].len(), HHC_BINS);
        for r in 20..300 {
            assert_eq!(d.values[100][r], 60.0, "bin {r} is rain");
        }
        assert!(d.values[100][500].is_nan(), "beyond the moment: unfilled");
        let expect_pct = 100.0 * (360.0 * D_GATES as f64) / (360.0 * HHC_BINS as f64);
        assert!(
            (d.pct_filled - expect_pct).abs() < 1.0,
            "pct_filled {} vs {expect_pct}",
            d.pct_filled,
        );
        assert!((d.highest_elev_deg - 0.5).abs() < 1e-6);
    }

    #[test]
    fn unusable_low_bins_climb_the_hybrid_ladder() {
        let t1 = tilt(
            0.5,
            &|_| G::V(30.0),
            &|i| if i < 200 { G::V(1.0) } else { G::Nd },
            &|i| if i < 200 { G::V(0.99) } else { G::Nd },
            &|i| if i < 200 { G::V(60.0) } else { G::Nd },
        );
        let t2 = rain_tilt(1.5, 0..D_GATES);
        let ml = MeltingLayer::flat(4.0);

        let one =
            compute_hhc(&[(0.5, t1.clone())], &params(), &ml, &hsda_far(), None).expect("computes");
        assert_eq!(one.values[50][100], 60.0);
        assert!(
            one.values[50][300].is_nan(),
            "no rate at the lowest cut, no higher cut to try",
        );

        let two = compute_hhc(&[(0.5, t1), (1.5, t2)], &params(), &ml, &hsda_far(), None)
            .expect("computes");
        assert_eq!(two.values[50][100], 60.0, "tilt 1's rain stands");
        assert_eq!(two.values[50][300], 60.0, "tilt 2 fills the pending bins");
    }

    #[test]
    fn no_echo_fills_and_blocks_higher_tilts() {
        let t1 = rain_tilt(0.5, 0..100);
        let t2 = rain_tilt(1.5, 0..D_GATES);
        let ml = MeltingLayer::flat(4.0);
        let d = compute_hhc(&[(0.5, t1), (1.5, t2)], &params(), &ml, &hsda_far(), None)
            .expect("computes");
        assert_eq!(d.values[50][50], 60.0);
        assert!(
            d.values[50][200].is_nan(),
            "tilt 1's no-echo filled the bin as ND; tilt 2's rain must not leak in",
        );
    }

    #[test]
    fn a_supplemental_cut_refreshes_the_lowest_cut_bins() {
        let t1 = rain_tilt(0.5, 0..D_GATES);
        let t2 = rain_tilt(1.5, 0..D_GATES);
        // The SAILS cut carries big drops instead of rain.
        let sails = tilt(
            0.5,
            &|_| G::V(35.0),
            &|_| G::V(3.0),
            &|_| G::V(0.98),
            &|_| G::V(60.0),
        );
        let ml = MeltingLayer::flat(4.0);
        let d = compute_hhc(
            &[(0.5, t1), (1.5, t2), (0.52, sails)],
            &params(),
            &ml,
            &hsda_far(),
            None,
        )
        .expect("computes");
        for r in 20..300 {
            assert_eq!(
                d.values[100][r], 80.0,
                "bin {r}: the supplemental cut's BD replaces the base cut's RA",
            );
        }
    }

    /// One whole-degree radial at an arbitrary azimuth, uniform in range.
    fn radial_at(az: f64, elev: f32, dbz: f64) -> Radial {
        let z: Vec<G> = (0..D_GATES).map(|_| G::V(dbz)).collect();
        let zdr: Vec<G> = (0..D_GATES).map(|_| G::V(1.0)).collect();
        let rho: Vec<G> = (0..D_GATES).map(|_| G::V(0.99)).collect();
        let phi: Vec<G> = (0..D_GATES).map(|_| G::V(60.0)).collect();
        Radial::new(
            0,
            0,
            az as f32,
            1.0,
            RadialStatus::IntermediateRadialData,
            1,
            elev,
            Some(m8(2.0, 66.0, &z)),
            None,
            None,
            Some(m8(16.0, 128.0, &zdr)),
            Some(m16(10.0, 2.0, &phi)),
            Some(m16(500.0, 2.0, &rho)),
            None,
        )
    }

    /// **Two radials on one whole degree still resolve to the later one.**
    #[test]
    fn two_radials_on_one_degree_resolve_to_the_later_one() {
        let radials = vec![
            radial_at(10.2, 0.5, 30.0),
            radial_at(10.7, 0.5, 55.0),
            radial_at(11.5, 0.5, 30.0),
        ];

        let inputs: Vec<DpInput> = radials.iter().filter_map(DpInput::from_radial).collect();
        let degrees: Vec<usize> = combine_sweep_dp(&inputs, true)
            .iter()
            .map(|c| (c.base.az.rem_euclid(360.0)) as usize % HHC_AZ)
            .collect();
        assert_eq!(
            degrees,
            vec![10, 10, 11],
            "the fixture's radials no longer collide on one degree; this proves nothing"
        );

        let rows = prepare_tilt(
            &radials,
            &params(),
            &MeltingLayer::flat(4.0),
            &hsda_far(),
            None,
            HcaOptions::primary(),
        )
        .expect("a tilt");
        let smz = rows[10].as_ref().expect("degree 10 is filled").smz[100];
        assert!(
            smz > 45.0,
            "degree 10 kept the 30 dBZ radial (smz {smz}), not the 55 dBZ one \
             that came after it in the sweep",
        );
    }
}
