pub mod archive;
pub mod chunks;
pub mod eet;
pub(crate) mod l3_values;
pub mod level3;
pub mod nrot;
mod palette;
pub mod render;
pub mod render_input;
pub mod scan;
pub mod sites;
pub mod sounding;
pub mod sources;
pub mod srm;
pub mod tls;
pub mod twin;
pub mod types;
pub mod volumetric;

pub use palette::{LegendScale, get_color_for_value, get_legend_scale};
