use super::*;

// Nothing below is computed with the code under test. Three sources:
//   (A) the HRRR GRIB2 file's own section 3 (La1/Lo1 is grid point (0,0));
//   (B) PROJ 9.8.1, the C implementation grib's `gridpoints-proj` delegated
//       to and therefore the behaviour this module must preserve;
//   (C) the EPSG Guidance Note 7-2 worked example for "Lambert Conic
//       Conformal (2SP)" (method 9802).

/// <= 11 cm anywhere on this grid: 1e-6° of latitude is 0.111 m at every
/// latitude (1° ≈ 111.2 km), while 1e-6° of longitude (1° ≈ 111.32·cos φ km)
/// runs 0.104 m at 21°N down to 0.075 m at 48°N. The latitude term
/// therefore sets the bound, and it is constant — even at the equator, where
/// the longitude term peaks at 0.1113 m, the worst case moves by 0.12 mm. So
/// this holds worldwide and needs no re-derivation for another domain.
///
/// Deliberately far tighter than the 3 km spacing: the failure mode guarded
/// against is systematic displacement (wrong earth radius, dropped central
/// meridian), which is tens of metres at minimum.
const HRRR_TOLERANCE_DEG: f64 = 1e-6;

#[track_caller]
fn assert_latlon_close(actual: (f64, f64), expected: (f64, f64), tol: f64, what: &str) {
    let (dlat, dlon) = ((actual.0 - expected.0).abs(), (actual.1 - expected.1).abs());
    assert!(
        dlat <= tol && dlon <= tol,
        "{what}: got ({:.8}, {:.8}), expected ({:.8}, {:.8}); \
             off by ({dlat:.3e}, {dlon:.3e})° > {tol:.1e}°",
        actual.0,
        actual.1,
        expected.0,
        expected.1,
    );
}

fn index_of(grid: &Template3_30, i: usize, j: usize) -> usize {
    // Scanning mode 0b0100_0000 is i-consecutive, so rows of `ni` points.
    j * grid.ni as usize + i
}

/// **Source (A) — the file's own section 3.** No external tool in the loop.
///
/// Not sufficient alone: `latlons` forward-projects La1/Lo1 and immediately
/// inverse-projects it, so corner (0,0) is algebraically invariant under any
/// change to the earth radius. Hence the far-corner tests below.
#[test]
fn first_grid_point_reproduces_the_files_own_la1_lo1() {
    let grid = hrrr_conus_grid();
    let points = latlons(&grid).unwrap();
    assert_eq!(points.len(), 1799 * 1059);
    assert_latlon_close(
        points[0],
        // Section 3: La1 = 21138123, Lo1 = 237280472 microdegrees.
        (21.138123, 237.280472 - 360.0),
        HRRR_TOLERANCE_DEG,
        "grid point (0,0) vs the file's La1/Lo1",
    );
}

/// **Source (B) — PROJ 9.8.1.**
///
/// Generated by forward-projecting La1/Lo1 with PROJ, stepping by
/// 3000 m per index exactly as `latlons` does, and inverse-projecting:
///
/// ```text
/// $ echo "-122.719528 21.138123" | proj -f "%.6f" \
///     +proj=lcc +a=6371229 +b=6371229 \
///     +lat_0=38.5 +lon_0=262.5 +lat_1=38.5 +lat_2=38.5
/// -2697520.142522  -1587306.152557
///
/// $ proj -I -f "%.8f" +proj=lcc +a=6371229 +b=6371229 \
///     +lat_0=38.5 +lon_0=262.5 +lat_1=38.5 +lat_2=38.5 <<EOF
/// -2697520.142522 -1587306.152557     # (i,j) = (   0,    0)
///  2696479.857478 -1587306.152557     # (i,j) = (1798,    0)
/// -2697520.142522  1586693.847443     # (i,j) = (   0, 1058)
///  2696479.857478  1586693.847443     # (i,j) = (1798, 1058)
///  -520.142522     -306.152557        # (i,j) = ( 899,  529)
/// EOF
/// -122.71952800  21.13812300
///  -72.28971849  21.14054663
/// -134.09547973  47.83862350
///  -60.91719277  47.84219502
///  -97.50597669  38.49724665
/// ```
///
/// PROJ's inverse of the first corner returns La1/Lo1 to all eight printed
/// decimals, which cross-validates source (B) against source (A).
const HRRR_CORNERS_FROM_PROJ: &[(usize, usize, f64, f64, &str)] = &[
    (0, 0, 21.138123_00, -122.719528_00, "SW corner (0,0)"),
    (1798, 0, 21.140546_63, -72.289718_49, "SE corner (ni-1,0)"),
    (0, 1058, 47.838623_50, -134.095479_73, "NW corner (0,nj-1)"),
    (
        1798,
        1058,
        47.842195_02,
        -60.917192_77,
        "NE corner (ni-1,nj-1)",
    ),
    (899, 529, 38.497246_65, -97.505976_69, "interior midpoint"),
];

/// All four corners plus an interior point against PROJ.
///
/// The interior point is not decoration: it sits ~500 m from the projection
/// origin (LoV 262.5 = -97.5, LaD 38.5), so it pins the origin placement
/// that the corners — all thousands of kilometres away — constrain only
/// weakly.
#[test]
fn hrrr_corners_and_interior_match_proj() {
    let grid = hrrr_conus_grid();
    let points = latlons(&grid).unwrap();
    for &(i, j, lat, lon, what) in HRRR_CORNERS_FROM_PROJ {
        assert_latlon_close(
            points[index_of(&grid, i, j)],
            (lat, lon),
            HRRR_TOLERANCE_DEG,
            what,
        );
    }
}

/// The `Lo1` the retired NOMADS filter path produced, which also projects
/// correctly.
///
/// That request always carried `subregion=&toplat=...&leftlon=...`. Those do
/// not subset a Lambert grid — the response was always the full 1799x1059
/// CONUS field — but they were not inert: NOMADS re-encoded the record
/// through wgrib2 rather than streaming it, re-rounding `Lo1` from 237280472
/// to **237280471** microdegrees and re-packing DRT 5.3 to DRT 5.0. S3 serves
/// the operational bytes, so the live decode path sees 5.3. grib handles both
/// in pure Rust, which is why dropping JPEG2000 and CCSDS is safe either way.
///
/// One microdegree of `Lo1` is ~10 cm at the anchor but rotates the grid
/// about the cone apex, so at the NE corner the two encodings differ by
/// 1.12e-6° — just over [`HRRR_TOLERANCE_DEG`]. Hence a separate fixture: a
/// tolerance wide enough for both would hide a real error.
///
/// **Source (B) — PROJ 9.8.1**, same procedure as
/// [`HRRR_CORNERS_FROM_PROJ`] but anchored at Lo1 = 237.280471:
///
/// ```text
/// $ echo "-122.719529 21.138123" | proj -f "%.6f" +proj=lcc \
///     +a=6371229 +b=6371229 +lat_0=38.5 +lon_0=262.5 +lat_1=38.5 +lat_2=38.5
/// -2697520.246793  -1587306.123248
///
/// $ proj -I -f "%.8f" ...same...   # corner offsets at 3000 m per index
/// -122.71952900  21.13812300
///  -72.28971934  21.14054711
/// -134.09548115  47.83862338
///  -60.91719389  47.84219562
///  -97.50597789  38.49724691
/// ```
#[test]
fn the_nomads_filter_reencodes_lo1_by_one_microdegree() {
    let mut grid = hrrr_conus_grid();
    grid.first_point_lon = 237_280_471;
    let points = latlons(&grid).unwrap();

    let from_proj: &[(usize, usize, f64, f64, &str)] = &[
        (0, 0, 21.138123_00, -122.719529_00, "SW"),
        (1798, 0, 21.140547_11, -72.289719_34, "SE"),
        (0, 1058, 47.838623_38, -134.095481_15, "NW"),
        (1798, 1058, 47.842195_62, -60.917193_89, "NE"),
        (899, 529, 38.497246_91, -97.505977_89, "interior"),
    ];
    for &(i, j, lat, lon, what) in from_proj {
        assert_latlon_close(
            points[index_of(&grid, i, j)],
            (lat, lon),
            HRRR_TOLERANCE_DEG,
            &format!("filter-CGI encoding, {what}"),
        );
    }

    // The two encodings really do disagree by more than the shared tolerance
    // at the far corner, so the fixtures cannot be swapped silently.
    let operational = latlons(&hrrr_conus_grid()).unwrap();
    let ne = index_of(&grid, 1798, 1058);
    let delta = (points[ne].1 - operational[ne].1).abs();
    assert!(
        delta > HRRR_TOLERANCE_DEG,
        "the two encodings differ by {delta:.3e}° at the NE corner, which is \
             within tolerance — this test no longer documents anything",
    );
    assert!(
        delta < 2.0 * HRRR_TOLERANCE_DEG,
        "the two encodings differ by {delta:.3e}° at the NE corner, far more \
             than one microdegree of Lo1 should cause",
    );
}

// ── The lazy geometry ─────────────────────────────────────────────────

/// [`LambertGrid::ij_at`] reproduces grib's `GridPointIndexIterator` in
/// closed form, which is what lets a point be answered without walking the
/// grid. Pinned against that iterator across **all sixteen** supported
/// scanning modes rather than against the reasoning behind it — HRRR only
/// ever sends 0b0100_0000, so the other fifteen have no other guard.
#[test]
fn the_flat_index_mapping_reproduces_gribs_scan_order() {
    use grib::def::grib2::template::param_set;
    let mut grid = hrrr_conus_grid();
    // Deliberately not square and not even, so a transposed or
    // off-by-one-row mapping cannot coincide with the right one.
    grid.ni = 5;
    grid.nj = 3;

    for high_nibble in 0..16u8 {
        let bits = high_nibble << 4;
        grid.scanning_mode = param_set::ScanningMode(bits);
        let expected: Vec<(usize, usize)> = grid.ij().unwrap().collect();
        let geometry = LambertGrid::from_template(&grid).unwrap();

        assert_eq!(expected.len(), geometry.len(), "mode {bits:#010b}");
        for (k, &(i, j)) in expected.iter().enumerate() {
            assert_eq!(
                geometry.ij_at(k),
                Some((i, j)),
                "mode {bits:#010b}: index {k}",
            );
            assert_eq!(
                geometry.index_of(i, j),
                k,
                "mode {bits:#010b}: point ({i}, {j})",
            );
        }
        assert_eq!(
            geometry.ij_at(expected.len()),
            None,
            "mode {bits:#010b}: one past the end must not wrap",
        );
    }
}

/// The size in [`LambertGrid`]'s own doc, **measured** rather than counted.
///
/// That figure read 88 for as long as two fields had existed without it being
/// updated. It is the whole reason to believe "constants, not arrays", and the
/// number is what a caller costing a cache entry reaches for — so it is pinned
/// here rather than left to be re-derived by whoever next doubts it.
///
/// 64-bit only: `usize` is four bytes on wasm32, where the same layout is 96.
#[test]
#[cfg(target_pointer_width = "64")]
fn the_documented_size_is_the_measured_one() {
    assert_eq!(
        std::mem::size_of::<LambertGrid>(),
        104,
        "LambertGrid's doc comment states this figure; update both together",
    );
}

/// The lazy form must be **bit-identical** to the eager one it replaced, at
/// every one of the 1,905,141 points — not close, identical: it is the same
/// arithmetic, and every PROJ-anchored assertion above is stated in terms of
/// [`latlons`].
#[test]
fn the_lazy_geometry_reproduces_the_eager_latlons() {
    let grid = hrrr_conus_grid();
    let eager = latlons(&grid).unwrap();
    let lazy = LambertGrid::from_template(&grid).unwrap();

    assert_eq!(lazy.len(), eager.len());
    for (k, &expected) in eager.iter().enumerate() {
        assert_eq!(lazy.latlon_at(k), Some(expected), "grid point {k}");
    }
    assert_eq!(lazy.latlon_at(eager.len()), None);
}

/// The tooltip's O(1) lookup must land where a scan over all 1.9 M points
/// would.
///
/// Sampled away from the anchor on purpose: `nearest` divides by the same
/// `dx`/`dy` the forward projection was anchored with, so grid point (0, 0)
/// resolves correctly even under a wrong step — the same blind-oracle shape
/// as the earth-radius corner case above.
#[test]
fn nearest_recovers_the_index_of_a_grid_point() {
    let grid = hrrr_conus_grid();
    let geometry = LambertGrid::from_template(&grid).unwrap();

    for &(i, j, _, _, what) in HRRR_CORNERS_FROM_PROJ {
        let (lat, lon) = geometry.latlon(i, j);
        assert_eq!(
            geometry.nearest(lat, lon),
            Some(geometry.index_of(i, j)),
            "{what}",
        );
    }

    // A third of a cell off-centre still rounds to the same point.
    let (lat, lon) = geometry.latlon(900, 530);
    let (nlat, nlon) = geometry.latlon(901, 531);
    assert_eq!(
        geometry.nearest(lat + (nlat - lat) / 3.0, lon + (nlon - lon) / 3.0),
        Some(geometry.index_of(900, 530)),
        "a point inside a cell must resolve to that cell",
    );
}

/// One cell past each edge, not a continent away.
///
/// The far-away cases below cannot see this: relaxing the upper bound to
/// `i > ni` admits `i == ni`, and under i-consecutive scanning
/// `index_of(ni, j)` is the *west* edge of row `j + 1` — an in-range index
/// holding a reading from 5,000 km away, which `values.get` will happily
/// return.
#[test]
fn nearest_refuses_the_cell_just_past_each_edge() {
    let grid = hrrr_conus_grid();
    let (ni, nj) = (grid.ni as usize, grid.nj as usize);
    let geometry = LambertGrid::from_template(&grid).unwrap();

    for &(i, j, what) in &[
        (ni, 0usize, "one column past the east edge"),
        (0usize, nj, "one row past the north edge"),
        (ni, nj, "past both edges"),
    ] {
        let (lat, lon) = geometry.latlon(i, j);
        assert_eq!(geometry.nearest(lat, lon), None, "{what}");
    }

    // Control: the last real point must still resolve, or the guard is
    // simply off by one the other way.
    let (lat, lon) = geometry.latlon(ni - 1, nj - 1);
    assert_eq!(
        geometry.nearest(lat, lon),
        Some(geometry.index_of(ni - 1, nj - 1)),
        "the far corner is inside the grid",
    );
}

/// [`LambertGrid::index_bounds`] is a closed form over a candidate set, not
/// a scan, so it is checked against the scan it replaces: every grid point
/// inside the box must fall inside the bounds it returns.
///
/// The second half is what stops it degenerating into `0..ni`, which would
/// satisfy the first half for ever: the answer must also be *tight*, within
/// a cell of the true extent of the contained points.
#[test]
fn index_bounds_brackets_exactly_the_points_inside_the_box() {
    let mut template = hrrr_conus_grid();
    template.ni = 120;
    template.nj = 90;
    let g = LambertGrid::from_template(&template).unwrap();

    // Spread over the grid, including boxes that straddle an edge, cover
    // everything and miss entirely. Degrees, absolute. `tight` is off for a
    // box that runs off the grid: it is then legitimately wider than any
    // point it contains, and only containment is meaningful.
    let (lat0, lon0) = g.latlon(60, 45);
    let boxes: &[(f64, f64, f64, f64, bool, &str)] = &[
        (
            lat0 - 0.2,
            lat0 + 0.2,
            lon0 - 0.2,
            lon0 + 0.2,
            true,
            "small interior",
        ),
        (
            lat0 - 0.5,
            lat0 + 0.5,
            lon0 - 0.8,
            lon0 + 0.8,
            true,
            "wide interior",
        ),
        (
            lat0 - 0.03,
            lat0 + 0.03,
            lon0 - 0.9,
            lon0 + 0.9,
            true,
            "a thin strip",
        ),
        (
            lat0 - 3.0,
            lat0 + 0.3,
            lon0 - 3.0,
            lon0 + 0.3,
            false,
            "over the SW corner",
        ),
        (0.0, 90.0, -180.0, 0.0, false, "a quarter of the planet"),
        (
            lat0 + 8.0,
            lat0 + 9.0,
            lon0,
            lon0 + 1.0,
            false,
            "well off the grid",
        ),
    ];

    for &(min_lat, max_lat, min_lon, max_lon, tight, what) in boxes {
        let (fi0, fi1, fj0, fj1) = g
            .index_bounds(min_lat, max_lat, min_lon, max_lon)
            .unwrap_or_else(|| panic!("{what}: no bounds"));

        let (mut ti0, mut ti1) = (usize::MAX, 0usize);
        let (mut tj0, mut tj1) = (usize::MAX, 0usize);
        let mut inside = 0;
        for j in 0..template.nj as usize {
            for i in 0..template.ni as usize {
                let (lat, lon) = g.latlon(i, j);
                if lat < min_lat || lat > max_lat || lon < min_lon || lon > max_lon {
                    continue;
                }
                inside += 1;
                assert!(
                    (fi0..=fi1).contains(&(i as f64)) && (fj0..=fj1).contains(&(j as f64)),
                    "{what}: point ({i}, {j}) is inside the box but outside \
                         i {fi0:.3}..{fi1:.3}, j {fj0:.3}..{fj1:.3}",
                );
                ti0 = ti0.min(i);
                ti1 = ti1.max(i);
                tj0 = tj0.min(j);
                tj1 = tj1.max(j);
            }
        }

        if !tight {
            continue;
        }
        assert!(
            inside > 0,
            "{what}: an empty box proves nothing about tightness"
        );
        // Two cells of slack: the bounds are over the continuous box, the
        // true extent over lattice points, and a thin box's corner need not
        // contain one. Nowhere near enough slack to admit a degenerate
        // `0..ni`, which is tens of cells out on these boxes.
        for (got, want, axis) in [
            (fi0, ti0 as f64, "i lower"),
            (fi1, ti1 as f64, "i upper"),
            (fj0, tj0 as f64, "j lower"),
            (fj1, tj1 as f64, "j upper"),
        ] {
            assert!(
                (got - want).abs() <= 2.0,
                "{what}: {axis} bound {got:.3} is {:.3} cells off the {want} \
                     the {inside} contained points actually reach",
                (got - want).abs(),
            );
        }
    }
}

/// Off the grid must be `None`, not a clamped edge point: the tooltip would
/// otherwise report a CONUS reading for a cursor over the Atlantic.
#[test]
fn nearest_refuses_a_point_outside_the_grid() {
    let geometry = LambertGrid::from_template(&hrrr_conus_grid()).unwrap();
    for &(lat, lon, what) in &[
        (51.5, -0.13, "London"),
        (-33.87, 151.21, "Sydney"),
        (21.14, -140.0, "west of the SW corner"),
        (60.0, -97.5, "north of the domain"),
        (10.0, -97.5, "south of the domain"),
    ] {
        assert_eq!(geometry.nearest(lat, lon), None, "{what}");
    }
}

/// A projection can agree with PROJ at sampled points and still be indexed
/// wrongly (transposed axes, sign flip on Dy). Scanning mode 0b0100_0000
/// scans +i west-to-east and +j south-to-north.
#[test]
fn grid_spans_conus_in_the_stated_scan_order() {
    let grid = hrrr_conus_grid();
    let points = latlons(&grid).unwrap();

    let sw = points[index_of(&grid, 0, 0)];
    let nw = points[index_of(&grid, 0, 1058)];
    let se = points[index_of(&grid, 1798, 0)];
    assert!(nw.0 > sw.0, "+j must run south to north: {sw:?} -> {nw:?}");
    assert!(se.1 > sw.1, "+i must run west to east: {sw:?} -> {se:?}");

    let (mut min_lat, mut max_lat) = (f64::MAX, f64::MIN);
    let (mut min_lon, mut max_lon) = (f64::MAX, f64::MIN);
    for &(lat, lon) in &points {
        min_lat = min_lat.min(lat);
        max_lat = max_lat.max(lat);
        min_lon = min_lon.min(lon);
        max_lon = max_lon.max(lon);
    }
    // NOAA's published HRRR CONUS domain: ~21.1N-52.6N, 134.1W-60.9W.
    // Loose on purpose; the tight numbers are the PROJ test's job.
    assert!(
        (21.0..22.0).contains(&min_lat) && (52.0..53.0).contains(&max_lat),
        "latitude span {min_lat}..{max_lat} is not the HRRR CONUS domain",
    );
    assert!(
        (-135.0..-133.0).contains(&min_lon) && (-61.5..-60.0).contains(&max_lon),
        "longitude span {min_lon}..{max_lon} is not the HRRR CONUS domain",
    );
}

/// Independent of every reference value above: asserts only that `forward`
/// and `inverse` are mutual inverses, which the PROJ test cannot see.
#[test]
fn forward_of_inverse_returns_the_original_grid_index() {
    let grid = hrrr_conus_grid();
    let projection =
        LambertConformalConic::new(6_371_229.0, 6_371_229.0, 38.5, 262.5, 38.5, 38.5).unwrap();
    let (x0, y0) = projection.forward(21.138123, 237.280472);
    let points = latlons(&grid).unwrap();

    for &(i, j, _, _, what) in HRRR_CORNERS_FROM_PROJ {
        let (lat, lon) = points[index_of(&grid, i, j)];
        let (x, y) = projection.forward(lat, lon);
        let (fi, fj) = ((x - x0) / 3000.0, (y - y0) / 3000.0);
        // 1e-6 of a 3 km cell is 3 mm.
        assert!(
            (fi - i as f64).abs() < 1e-6 && (fj - j as f64).abs() < 1e-6,
            "{what}: round trip gave index ({fi}, {fj}), expected ({i}, {j})",
        );
    }
}

/// **Hand-worked invariant.** At `phi = lat_0`, `rho = rho0`; at
/// `lambda = lon_0`, `theta = 0`; so eq. 14-1/14-2 give `x = y = 0` and
/// `inverse(0, 0) == (lat_0, lon_0)` exactly for any valid parameter set.
/// A self-consistent but individually wrong cone constant, scale factor or
/// origin radius survives a single-point check but not this across all four.
#[test]
fn projection_origin_inverts_to_lat0_lon0() {
    let cases: &[(f64, f64, f64, f64, f64, f64, &str)] = &[
        // (a, b, lat_0, lon_0, lat_1, lat_2, label)
        (
            6_371_229.0,
            6_371_229.0,
            38.5,
            262.5,
            38.5,
            38.5,
            "HRRR (tangent, sphere)",
        ),
        (
            6_371_229.0,
            6_371_229.0,
            38.5,
            -97.5,
            30.0,
            60.0,
            "secant, sphere",
        ),
        (
            6_378_206.4,
            6_356_583.8,
            27.833333,
            -99.0,
            28.383333,
            30.283333,
            "secant, ellipsoid",
        ),
        (
            6_371_229.0,
            6_371_229.0,
            -38.5,
            145.0,
            -30.0,
            -60.0,
            "southern cone",
        ),
    ];
    for &(a, b, lat0, lon0, lat1, lat2, label) in cases {
        let p = LambertConformalConic::new(a, b, lat0, lon0, lat1, lat2).unwrap();
        let (lat, lon) = p.inverse(0.0, 0.0);
        assert!(
            (lat - lat0).abs() < 1e-9 && (lon - lon0).abs() < 1e-9,
            "{label}: inverse(0,0) = ({lat}, {lon}), expected ({lat0}, {lon0})",
        );
    }
}

/// **Hand-worked invariant.** `n = sin(38.5°) = 0.6225146366376195`, from
/// `f64::sin` rather than from any projection code. The tangent branch is the
/// only one HRRR uses and the one whose formula is not the textbook one —
/// Snyder eq. 15-4 is 0/0 at `lat_1 == lat_2` and gives NaN.
#[test]
fn tangent_cone_constant_is_sin_of_the_standard_parallel() {
    let tangent =
        LambertConformalConic::new(6_371_229.0, 6_371_229.0, 38.5, 262.5, 38.5, 38.5).unwrap();
    let expected = 38.5_f64.to_radians().sin();
    assert!(
        (tangent.n - expected).abs() < 1e-15,
        "tangent cone constant {} != sin(38.5°) = {expected}",
        tangent.n,
    );
    assert!(
        tangent.n.is_finite(),
        "tangent branch produced {}",
        tangent.n
    );
}

/// The tangent cone constant must come from **Latin1, not LaD**.
///
/// Every other fixture here is HRRR-shaped, where `LaD == Latin1 == Latin2
/// == 38.5°`, so `sin(LaD)` and `sin(Latin1)` are indistinguishable and that
/// mutation survives the whole suite. Template 3.30 does not require them to
/// agree, so this separates them: LaD = 45°, Latin1 = Latin2 = 30°.
///
/// **Source (B) — PROJ 9.8.1:**
///
/// ```text
/// $ proj -f "%.6f" +proj=lcc +a=6371229 +b=6371229 \
///       +lat_0=45 +lon_0=-97.5 +lat_1=30 +lat_2=30 <<EOF
/// -97.5 30
/// -110 25
/// -85 40
/// -97.5 45
/// EOF
///        0.000000  -1688204.721066
/// -1261983.214498  -2175998.860672
///  1079682.808600   -511425.736939
///        0.000000         0.000000
/// ```
///
/// The last row is the origin invariant, which holds under the mutation too
/// (rho0 is built from the same `n`), hence the other three rows.
#[test]
fn tangent_cone_constant_follows_latin1_not_lad() {
    let p = LambertConformalConic::new(6_371_229.0, 6_371_229.0, 45.0, -97.5, 30.0, 30.0).unwrap();

    let expected_n = 30.0_f64.to_radians().sin();
    assert!(
        (p.n - expected_n).abs() < 1e-15,
        "cone constant {} is not sin(Latin1) = sin(30°) = {expected_n}; \
             sin(LaD) = sin(45°) = {} would be wrong",
        p.n,
        45.0_f64.to_radians().sin(),
    );

    // Tolerance is 1 mm, the printed precision of the reference.
    let from_proj: &[(f64, f64, f64, f64)] = &[
        (30.0, -97.5, 0.0, -1_688_204.721066),
        (25.0, -110.0, -1_261_983.214498, -2_175_998.860672),
        (40.0, -85.0, 1_079_682.808600, -511_425.736939),
        (45.0, -97.5, 0.0, 0.0),
    ];
    for &(lat, lon, want_x, want_y) in from_proj {
        let (x, y) = p.forward(lat, lon);
        assert!(
            (x - want_x).abs() < 1e-3 && (y - want_y).abs() < 1e-3,
            "LaD=45/Latin=30 forward ({lat}, {lon}): got ({x:.6}, {y:.6}), \
                 PROJ says ({want_x:.6}, {want_y:.6})",
        );
        let (rlat, rlon) = p.inverse(x, y);
        assert!(
            (rlat - lat).abs() < 1e-9 && (rlon - lon).abs() < 1e-9,
            "round trip ({lat}, {lon}) -> ({rlat}, {rlon})",
        );
    }
}

/// The two branches must be one continuous function. Expected values come
/// from `f64::sin` of the mean parallel, not from the projection.
#[test]
fn secant_cone_constant_approaches_the_tangent_limit() {
    for delta in [1.0_f64, 0.1, 0.01, 0.001] {
        let (lat1, lat2) = (38.5 - delta / 2.0, 38.5 + delta / 2.0);
        let secant =
            LambertConformalConic::new(6_371_229.0, 6_371_229.0, 38.5, 262.5, lat1, lat2).unwrap();
        // The secant cone constant tends to sin(38.5°) as δ -> 0 with error
        // O(δ²), so the bound is δ²-scaled.
        let expected = 38.5_f64.to_radians().sin();
        let bound = 1e-3 * delta * delta;
        assert!(
            (secant.n - expected).abs() < bound,
            "secant n for parallels ±{}° = {}, tangent limit {expected}, \
                 difference exceeds the O(δ²) bound {bound}",
            delta / 2.0,
            secant.n,
        );
        // And it must genuinely take the secant branch.
        assert_ne!(
            secant.n, expected,
            "delta={delta} was absorbed by the tangent epsilon",
        );
    }
}

/// Swapping the standard parallels is the one obvious mutation here that is
/// *not* a bug: eq. 15-4 is antisymmetric in numerator and denominator, and
/// eq. 15-2 gives the same `F` from either parallel by construction. No test
/// suite can distinguish the orderings. PROJ 9.8.1 agrees — the EPSG example
/// below differs by 3 nm between the two orders.
#[test]
fn exchanging_the_standard_parallels_is_a_no_op() {
    let a = 6_378_206.400;
    let b = a * (1.0 - 1.0 / 294.97870);
    let (lat0, lon0) = (27.0 + 50.0 / 60.0, -99.0);
    let (lat1, lat2) = (28.0 + 23.0 / 60.0, 30.0 + 17.0 / 60.0);

    let normal = LambertConformalConic::new(a, b, lat0, lon0, lat1, lat2).unwrap();
    let swapped = LambertConformalConic::new(a, b, lat0, lon0, lat2, lat1).unwrap();

    assert!(
        (normal.n - swapped.n).abs() < 1e-15,
        "cone constant differs"
    );
    assert!(
        (normal.big_f - swapped.big_f).abs() / normal.big_f < 1e-12,
        "scale factor differs: {} vs {}",
        normal.big_f,
        swapped.big_f,
    );
    for (lat, lon) in [(28.5, -96.0), (31.0, -102.0), (26.0, -95.0)] {
        let (x1, y1) = normal.forward(lat, lon);
        let (x2, y2) = swapped.forward(lat, lon);
        assert!(
            (x1 - x2).abs() < 1e-6 && (y1 - y2).abs() < 1e-6,
            "({lat}, {lon}): ({x1}, {y1}) vs ({x2}, {y2})",
        );
    }
}

/// **Source (C) — EPSG Guidance Note 7-2, method 9802
/// "Lambert Conic Conformal (2SP)", published worked example.**
///
/// The secant *and* ellipsoidal path, which no real input exercises: HRRR is
/// tangent on a sphere, and grib's only upstream Lambert fixture
/// (`ds.critfireo.bin`) is also tangent, at Latin1 = Latin2 = 25°. Without
/// this the secant and ellipsoid branches ship unverified.
///
/// From the EPSG guidance note:
///
/// ```text
///   Ellipsoid:  Clarke 1866   a = 6378206.400 m   1/f = 294.97870
///   Latitude of false origin        27°50'00"N  = 27.833333°
///   Longitude of false origin       99°00'00"W  = -99.0°
///   First  standard parallel        28°23'00"N  = 28.383333°
///   Second standard parallel        30°17'00"N  = 30.283333°
///   Easting  at false origin  2000000.00 US survey feet
///   Northing at false origin        0.00 US survey feet
///
///   Forward, for  latitude 28°30'00"N, longitude 96°00'00"W:
///     Easting  E = 2963503.91 US survey feet
///     Northing N =  254759.80 US survey feet
/// ```
///
/// This module has no false easting/northing (nor does grib's PROJ string),
/// so the offsets are applied in the test. 1 US survey foot = 1200/3937 m.
///
/// PROJ 9.8.1 gives (293676.579980, 77650.942539) m against the published
/// (293676.5791, 77650.9423) m — sub-millimetre, so (B) and (C) corroborate.
#[test]
fn secant_ellipsoidal_matches_the_epsg_published_worked_example() {
    const US_SURVEY_FOOT_M: f64 = 1200.0 / 3937.0;
    const FALSE_EASTING_USFT: f64 = 2_000_000.00;
    const FALSE_NORTHING_USFT: f64 = 0.00;

    // Clarke 1866, from the same guidance note.
    let a = 6_378_206.400;
    let inv_f = 294.97870;
    let b = a * (1.0 - 1.0 / inv_f);

    let p = LambertConformalConic::new(
        a,
        b,
        27.0 + 50.0 / 60.0, // 27°50'N
        -99.0,
        28.0 + 23.0 / 60.0, // 28°23'N
        30.0 + 17.0 / 60.0, // 30°17'N
    )
    .unwrap();

    // Forward.
    let (x, y) = p.forward(28.5, -96.0);
    let easting_usft = x / US_SURVEY_FOOT_M + FALSE_EASTING_USFT;
    let northing_usft = y / US_SURVEY_FOOT_M + FALSE_NORTHING_USFT;

    // The guidance note prints its expected coordinates to 0.01 US survey
    // feet (3 mm), so that rounding is the floor on agreement; 0.02 US
    // survey feet (6 mm) is the tightest honest bound.
    assert!(
        (easting_usft - 2_963_503.91).abs() < 0.02,
        "EPSG 9802 easting: got {easting_usft:.2} usft, expected 2963503.91",
    );
    assert!(
        (northing_usft - 254_759.80).abs() < 0.02,
        "EPSG 9802 northing: got {northing_usft:.2} usft, expected 254759.80",
    );

    // Inverse of the published coordinates must return the published
    // geodetic position. The note gives 6 significant decimals of a
    // degree; 1e-7° is ~11 mm, comfortably inside the 3 mm rounding of the
    // easting/northing it is derived from.
    let (lat, lon) = p.inverse(
        (2_963_503.91 - FALSE_EASTING_USFT) * US_SURVEY_FOOT_M,
        (254_759.80 - FALSE_NORTHING_USFT) * US_SURVEY_FOOT_M,
    );
    assert!(
        (lat - 28.5).abs() < 1e-7 && (lon - (-96.0)).abs() < 1e-7,
        "EPSG 9802 inverse: got ({lat:.9}, {lon:.9}), expected (28.5, -96.0)",
    );
}

/// Without this, the ellipsoidal machinery could be dead code and the EPSG
/// test would still pass. Measured separation at the EPSG test point is
/// ~332 m in northing; the 100 m bound is a floor, not a fitted value.
#[test]
fn dropping_the_eccentricity_would_fail_the_epsg_example() {
    const US_SURVEY_FOOT_M: f64 = 1200.0 / 3937.0;
    let a = 6_378_206.400;
    let b = a * (1.0 - 1.0 / 294.97870);
    let (lat0, lon0, lat1, lat2) = (
        27.0 + 50.0 / 60.0,
        -99.0,
        28.0 + 23.0 / 60.0,
        30.0 + 17.0 / 60.0,
    );

    let ellipsoid = LambertConformalConic::new(a, b, lat0, lon0, lat1, lat2).unwrap();
    let sphere = LambertConformalConic::new(a, a, lat0, lon0, lat1, lat2).unwrap();

    assert!(
        ellipsoid.e > 0.0,
        "Clarke 1866 must have non-zero eccentricity"
    );
    assert_eq!(sphere.e, 0.0, "a == b must give exactly zero eccentricity");

    // Distance between the two answers at the EPSG test point.
    let (ex, ey) = ellipsoid.forward(28.5, -96.0);
    let (sx, sy) = sphere.forward(28.5, -96.0);
    let separation = ((ex - sx).powi(2) + (ey - sy).powi(2)).sqrt();
    assert!(
        separation > 100.0,
        "sphere and ellipsoid differ by only {separation} m at the EPSG \
             test point — the eccentricity is not reaching the projection",
    );

    let sphere_northing_usft = sy / US_SURVEY_FOOT_M;
    assert!(
        (sphere_northing_usft - 254_759.80).abs() > 100.0,
        "a spherical projection would still pass the EPSG check \
             (northing {sphere_northing_usft:.2} usft vs published 254759.80), \
             so that test proves nothing about the ellipsoidal path",
    );

    // The iteration must converge, not merely run.
    let (lat, lon) = ellipsoid.inverse(ex, ey);
    assert!(
        (lat - 28.5).abs() < 1e-9 && (lon + 96.0).abs() < 1e-9,
        "ellipsoidal round trip drifted to ({lat}, {lon})",
    );
}

/// A southern-hemisphere cone gives `n < 0`, which flips the sign
/// conventions in Snyder eq. 15-11 and 14-11. Untested, that path silently
/// mirrors the grid.
///
/// **Source (B) — PROJ 9.8.1**, forward direction:
///
/// ```text
/// $ proj -f "%.6f" +proj=lcc +a=6371229 +b=6371229 \
///       +lat_0=-38.5 +lon_0=145 +lat_1=-30 +lat_2=-60 <<EOF
/// 150 -35
/// 140 -45
/// 170 -20
/// EOF
///  446832.877539    366322.927131
/// -379422.797189   -711785.038895
/// 2719239.664947   1644373.250769
/// ```
///
/// Tolerance is 1 mm, which is the printed precision of the reference.
#[test]
fn southern_cone_matches_proj_and_round_trips() {
    let p =
        LambertConformalConic::new(6_371_229.0, 6_371_229.0, -38.5, 145.0, -30.0, -60.0).unwrap();
    assert!(
        p.n < 0.0,
        "southern parallels must give a negative cone constant"
    );

    let from_proj: &[(f64, f64, f64, f64)] = &[
        (-35.0, 150.0, 446_832.877539, 366_322.927131),
        (-45.0, 140.0, -379_422.797189, -711_785.038895),
        (-20.0, 170.0, 2_719_239.664947, 1_644_373.250769),
    ];
    for &(lat, lon, want_x, want_y) in from_proj {
        let (x, y) = p.forward(lat, lon);
        assert!(
            (x - want_x).abs() < 1e-3 && (y - want_y).abs() < 1e-3,
            "southern cone forward ({lat}, {lon}): got ({x:.6}, {y:.6}), \
                 PROJ says ({want_x:.6}, {want_y:.6})",
        );
        let (rlat, rlon) = p.inverse(x, y);
        assert!(
            (rlat - lat).abs() < 1e-9 && (rlon - lon).abs() < 1e-9,
            "southern cone round trip ({lat}, {lon}) -> ({x}, {y}) -> ({rlat}, {rlon})",
        );
    }
}

/// Degenerate parameter sets must be rejected, not silently produce NaN
/// grids that render as an empty overlay.
#[test]
fn degenerate_parameters_are_rejected() {
    // lat_1 == -lat_2: the cone opens into a cylinder, n == 0.
    assert!(
        LambertConformalConic::new(6_371_229.0, 6_371_229.0, 0.0, 0.0, -30.0, 30.0).is_err(),
        "parallels symmetric about the equator must be rejected",
    );
    // Standard parallel at a pole.
    assert!(
        LambertConformalConic::new(6_371_229.0, 6_371_229.0, 45.0, 0.0, 90.0, 45.0).is_err(),
        "a standard parallel at the pole must be rejected",
    );
    // Nonsense axes.
    assert!(LambertConformalConic::new(0.0, 0.0, 38.5, 0.0, 38.5, 38.5).is_err());
    assert!(
        LambertConformalConic::new(6_356_752.0, 6_378_137.0, 38.5, 0.0, 38.5, 38.5).is_err(),
        "semi-minor axis larger than semi-major must be rejected",
    );
    // Unknown earth-shape code must surface as an error from `latlons`,
    // not a panic.
    let mut grid = hrrr_conus_grid();
    grid.earth_shape.shape = 200;
    assert!(
        latlons(&grid).is_err(),
        "unknown Code Table 3.2 value must error"
    );
}

/// Deliberately not a bit-for-bit clone of grib's `normalize_latlon`: grib's
/// `(lon + 540) % 360 - 180` keeps the sign of the dividend and returns
/// out-of-range values below -540° (-600° -> -240°), where `rem_euclid`
/// gives the correct +120°. The two agree above -540°, which covers every
/// longitude a GRIB2 grid can encode, so the divergence is unreachable here.
#[test]
fn longitude_normalization_lands_in_the_expected_half_open_range() {
    for (input, expected) in [
        (-180.0, -180.0),
        (0.0, 0.0),
        (179.0, 179.0),
        (180.0, -180.0),
        (360.0, 0.0),
        (540.0, -180.0),
        (237.280472, -122.719528),
        (262.5, -97.5),
    ] {
        let got = normalize_longitude_degrees(input);
        assert!(
            (got - expected).abs() < 1e-9,
            "normalize({input}) = {got}, expected {expected}",
        );
    }
}

/// The scanning-mode sign rules must actually be applied. HRRR scans +i/+j,
/// so flipping the bits must move the grid, and must move it the other way.
#[test]
fn scanning_mode_flips_the_grid_walk() {
    use grib::def::grib2::template::param_set::ScanningMode;

    let grid = hrrr_conus_grid();
    let forward = latlons(&grid).unwrap();

    // 0b1100_0000: -i (bit 7 set), +j.
    let mut flipped_i = hrrr_conus_grid();
    flipped_i.scanning_mode = ScanningMode(0b1100_0000);
    let west = latlons(&flipped_i).unwrap();

    // 0b0000_0000: +i, -j (bit 6 clear).
    let mut flipped_j = hrrr_conus_grid();
    flipped_j.scanning_mode = ScanningMode(0b0000_0000);
    let south = latlons(&flipped_j).unwrap();

    // Point (0,0) is La1/Lo1 in every case — it is the anchor.
    for set in [&forward, &west, &south] {
        assert_latlon_close(
            set[0],
            (21.138123, -122.719528),
            HRRR_TOLERANCE_DEG,
            "anchor point is La1/Lo1 regardless of scan direction",
        );
    }

    let i1 = index_of(&grid, 1, 0);
    let j1 = index_of(&grid, 0, 1);
    assert!(
        forward[i1].1 > forward[0].1 && west[i1].1 < west[0].1,
        "flipping the i scan bit must reverse the longitude step: \
             +i gave {} -> {}, -i gave {} -> {}",
        forward[0].1,
        forward[i1].1,
        west[0].1,
        west[i1].1,
    );
    assert!(
        forward[j1].0 > forward[0].0 && south[j1].0 < south[0].0,
        "flipping the j scan bit must reverse the latitude step: \
             +j gave {} -> {}, -j gave {} -> {}",
        forward[0].0,
        forward[j1].0,
        south[0].0,
        south[j1].0,
    );
}
